name: Setup Repository

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository to set up (format: owner/repo)'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout concat-script repository
        uses: actions/checkout@v3
        with:
          repository: johndavis92790/concat-script
          path: concat-script

      - name: Set up repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Setting up ${{ github.event.inputs.repo }}"
          git clone https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.event.inputs.repo }}.git
          cd $(echo ${{ github.event.inputs.repo }} | cut -d'/' -f2)
          echo "Creating .gitignore"
          echo "output.md" >> .gitignore
          echo "Creating .vscode/ directory"
          mkdir -p .vscode/
          echo "Copying tasks.json"
          cp ../concat-script/.vscode/tasks.json .vscode/
          echo "Installing dependencies"
          npm install puppeteer cross-spawn prettier clipboardy --force
          echo "Creating .github/workflows directory"
          mkdir -p .github/workflows
          echo "Copying update-script.yml"
          cp ../concat-script/.github/workflows/update-script.yml .github/workflows/
          echo "Copying concat.js"
          cp ../concat-script/concat.js .
          echo "Adding changes"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          echo "Committing changes"
          git commit -m "Add setup files"
          echo "Pushing changes"
          git push https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.event.inputs.repo }}.git